### PR TITLE
Add an alternative cellular automata wrapper for chemical emissions

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This is part of an effort to add chemistry data assimilation to the GEFS model. We plan on expanding this work to a more sophisticated algorithm that models the spread of forest fires. 

See also:

https://github.com/NOAA-GSL/ufs-weather-model/pull/85
https://github.com/NOAA-GSL/fv3atm/pull/94
https://github.com/NOAA-GSL/ccpp-physics/pull/94

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
I assume `cellular_automata_sgs_emis.F90` is sufficiently different from the existing `cellular_automata_sgs.F90` so that combining the two files doesn't make any sense.

**Comment by SamuelTrahanNOAA** [comment]
> I assume cellular_automata_sgs_emis.F90 is sufficiently different from the existing cellular_automata_sgs.F90 so that combining the two files doesn't make any sense.

Yes, but there are parallel efforts to rearrange the stochastic_physics. This code may end up somewhere else in that package eventually.

**Review by DomHeinzeller — APPROVED** [review]

**Comment by lisa-bengtsson** [comment]
This will not work once this updated PR is merged: https://github.com/noaa-psd/stochastic_physics/pull/41 because the argument list to update_cells_sgs will change. If this PR can not wait is there a possibility to create a duplicate update_cells_sgs_emiss or similar to avoid this conflict? @climbfuji @SamuelTrahanNOAA

**Comment by SamuelTrahanNOAA** [comment]
@lisa-bengtsson 

To merge your code to gsl/develop, we would have to update ufs-weather-model and FV3 in gsl's fork to support the new stochastic_physics code. We can't do that yet because it would impact many other projects. We may be stuck with the older version of stochastic_physics for a few more weeks. Also, gsd-chem needs to be merged into whatever new FV3 and ccpp we receive.

Looking at the new code, I don't think it would be terribly difficult to modify our version to call the new update_cells_sgs, once gsl/develop is updated. The arguments have not fundamentally changed, other than adding restart capability. Is that correct?

I think the solution is this:

1. Make a gsl/develop-chem branch of stochastic_physics, as we do with other repos already.
2. Wait for gsl/develop to receive the new changes from stochastic_physics
3. Update the chemistry CA code in stochastic_physics
4. Merge gsl/develop to gsl/develop-chem

**Comment by lisa-bengtsson** [comment]
Thanks Sam, I realize now this is in a fork of the ufs-weather-model and not feeding back into the authoritative repository. We should discuss before you bring your development to the HEAD of the ufs-weather-model in the future. Thanks.

**Comment by SamuelTrahanNOAA** [comment]
> Thanks Sam, I realize now this is in a fork of the ufs-weather-model and not feeding back into the authoritative repository. We should discuss before you bring your development to the HEAD of the ufs-weather-model in the future. Thanks.

These stochastic_physics changes aren't useful without the rest of gsd-chem. The gsd-chem is woven throughout ufs-weather-model, FV3, ccpp/physics, GOCART, and now stochastic_physics. Unfortunately, gsd-chem has not been merged to the authoritative repositories yet because it is still undergoing refactoring. Hopefully that won't go on for too much longer, and then we can merge back, so everyone can enjoy stochastic perturbations to their chemical emissions.

I could merge just the stochastic_physics changes to the central repositories, but you'd have no way to run it.

**Comment by lisa-bengtsson** [comment]
Thanks for clarifying Samuel, it makes more sense to me now. The merge of gsd-chem is a bigger question. You may want to use some of my recent updates to the CA domain and the restart capability in the future, we can discuss offline how to get that into your fork.

**Pull request merged**
